meta_title: "RefuGapp"
meta_description: "Fill the gap between locals and refugees."
meta_image: "colorful_refugapp.png" # Une image dans votre dossier app/assets/images/
twitter_account: "@GinaaGold"
